[[headers]]
  for = "/cache.appcache"
  [headers.values]
    Content-Type = "text/cache-manifest"
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "no-cache"
